logger:
  savePath: 'log'
  maxSize: 5
  maxAge: 400
  maxBackups: 1000
  isCompress: true
  logLevel: 'debug'

database:
  mysql:
    addr: 49.234.42.190
    port: 3306
    username: csademo
    password: 'BtBBmGBd7Y8BK7EA'
    db: csademo
    charset: utf8mb4
    connMaxIdleTime: '180s'
    connMaxLifeTime: '1800s'
    maxIdleConns: 100
    maxOpenConns: 500
  redis:
    addr: 49.234.42.190
    port: 6379
    username:
    password: "000415"
    db: 0
    poolSize: 10000
